/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6_jamilgarcia;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author JamilGarcía
 */
public class Principal extends javax.swing.JFrame {

    String userPrin;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        Login.setVisible(true);
        //boolean visible = false;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_login_user = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pf_login_pass = new javax.swing.JPasswordField();
        b_login_login = new javax.swing.JButton();
        b_login_Registrarse = new javax.swing.JButton();
        Register = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_register_nombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_register_user = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_register_password = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jd_register_fecha = new com.toedter.calendar.JDateChooser();
        b_register_Register = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_contactos = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_mensajeEs = new javax.swing.JTextArea();
        b_send = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_conversacion = new javax.swing.JList<>();

        Login.setMinimumSize(new java.awt.Dimension(500, 460));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setText("Login");

        jLabel4.setText("User:");

        jLabel5.setText("Password:");

        b_login_login.setText("Login");
        b_login_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_login_loginMouseClicked(evt);
            }
        });

        b_login_Registrarse.setText("Registrarse");
        b_login_Registrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_login_RegistrarseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login.getContentPane());
        Login.getContentPane().setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel3))
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_login_user)
                            .addComponent(pf_login_pass, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)))
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(b_login_login))
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(b_login_Registrarse)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_login_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pf_login_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(b_login_login)
                .addGap(42, 42, 42)
                .addComponent(b_login_Registrarse)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        Register.setMinimumSize(new java.awt.Dimension(542, 445));

        jLabel6.setText("Register");

        jLabel7.setText("Nombre:");

        jLabel8.setText("User:");

        jLabel9.setText("Password:");

        jLabel10.setText("Fecha de Nacimiento:");

        b_register_Register.setText("Register");
        b_register_Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_register_RegisterMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout RegisterLayout = new javax.swing.GroupLayout(Register.getContentPane());
        Register.getContentPane().setLayout(RegisterLayout);
        RegisterLayout.setHorizontalGroup(
            RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterLayout.createSequentialGroup()
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel6))
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(34, 34, 34)
                        .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_register_nombre)
                            .addComponent(tf_register_user)
                            .addComponent(tf_register_password)
                            .addComponent(jd_register_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)))
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(b_register_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        RegisterLayout.setVerticalGroup(
            RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel6)
                .addGap(47, 47, 47)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_register_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_register_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_register_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jd_register_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(b_register_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1257, 819));

        jLabel1.setText("Conversacion:");

        jLabel2.setText("Contactos:");

        jl_contactos.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl_contactos);

        ta_mensajeEs.setColumns(20);
        ta_mensajeEs.setRows(5);
        jScrollPane3.setViewportView(ta_mensajeEs);

        b_send.setText("Send");
        b_send.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_sendMouseClicked(evt);
            }
        });

        jl_conversacion.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(jl_conversacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_send, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(b_send, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_login_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_login_loginMouseClicked
        // TODO add your handling code here:

        DefaultListModel listaContacts = (DefaultListModel) jl_contactos.getModel();
        for (AdminUsers U : Users) {
            listaContacts.addElement(U);
        }
        
        File f = null;
        Scanner sc = null;
        String usuario = tf_login_user.getText();
        String pass = pf_login_pass.getText();
        try {
            //System.out.println("f");
            f = new File("./ficheros/Users.txt");
            //System.out.println("u");
            sc = new Scanner(f);
            //System.out.println("n");
            sc.useDelimiter(";");

            String n, u, p;
            int e;
            while (sc.hasNext()) {
                //System.out.println("c");
                n = sc.next();
                u = sc.next();
                p = sc.next();
                e = sc.nextInt();
                
                if (usuario.equals(u)) {
                    userPrin = u;
                    if (pass.equals(p)) {
                        new Principal().setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(this, "Contraseña incorrecta");
                    }
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Algo salio mal");
        }
        sc.close();
    }//GEN-LAST:event_b_login_loginMouseClicked

    private void b_login_RegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_login_RegistrarseMouseClicked
        // TODO add your handling code here:
        Register.setVisible(true);
        Login.setVisible(false);

    }//GEN-LAST:event_b_login_RegistrarseMouseClicked

    private void b_sendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_sendMouseClicked
        // TODO add your handling code here:
        DefaultListModel lista = (DefaultListModel) jl_conversacion.getModel();
        String mensaje = ta_mensajeEs.getText();
        lista.addElement(userPrin + ": " + mensaje);
        for (int i = 0; i < mensaje.length(); i++) {
            if (mensaje.charAt(i) == ('1')) {
                lista.addElement("Maquina: Funciona 1");
            }
            if (mensaje.charAt(i) == ('2')) {
                lista.addElement("Maquina: Funciona 2");
            }
            if (mensaje.charAt(i) == ('3')) {
                lista.addElement("Maquina: Funciona 3");
            }
            if (mensaje.charAt(i) == ('4')) {
                lista.addElement("Maquina: Funciona 4");
            }
        }
        ta_mensajeEs.setText("");

    }//GEN-LAST:event_b_sendMouseClicked

    private void b_register_RegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_register_RegisterMouseClicked
        // TODO add your handling code here:
        String nombre, user, password;
        Date fecha;
        int edad;
        boolean b = true;
        nombre = tf_register_nombre.getText();

        File f = null;
        Scanner sc = null;
        user = tf_register_user.getText();
        try {
            f = new File("./ficheros/Users.txt");
            sc = new Scanner(f);
            sc.useDelimiter(";");
            String n, u, p;
            int e;
            while (sc.hasNext()) {
                n = sc.next();
                u = sc.next();
                p = sc.next();
                e = sc.nextInt();
                if (user.equals(u)) {
                    b = false;
                }
                //System.out.println("Funciona");
            }
        } catch (Exception e) {
        }
        sc.close();

        edad = 20 - (jd_register_fecha.getDate().getYear() - 100);
        System.out.println(edad);
        if (edad < 13) {
            b = false;
        }

        if (b == true) {
            try {
                FileWriter fw = null;
                BufferedWriter bw = null;
                try {
                    f = new File("./ficheros/Users.txt");
                    fw = new FileWriter(f, true); //OJO
                    bw = new BufferedWriter(fw);
                    String u, p, n;
                    int e;
                    n = tf_register_nombre.getText();
                    u = tf_register_password.getText();
                    p = tf_register_password.getText();
                    e = edad;

                    bw.write(n + ";");
                    bw.write(u + ";");
                    bw.write(p + ";");
                    bw.write(e + ";");
                    bw.flush();

                } catch (Exception e) {
                    e.printStackTrace();
                }

                tf_register_nombre.setText("");
                tf_register_password.setText("");
                tf_register_user.setText("");
                
                bw.close();
                fw.close();
                JOptionPane.showMessageDialog(this, "Guardado Con Exito");
                Login.setVisible(true);
                Register.setVisible(false);
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Usuario no permitido");
        }

    }//GEN-LAST:event_b_register_RegisterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Login;
    private javax.swing.JFrame Register;
    private javax.swing.JButton b_login_Registrarse;
    private javax.swing.JButton b_login_login;
    private javax.swing.JButton b_register_Register;
    private javax.swing.JButton b_send;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private com.toedter.calendar.JDateChooser jd_register_fecha;
    private javax.swing.JList<String> jl_contactos;
    private javax.swing.JList<String> jl_conversacion;
    private javax.swing.JPasswordField pf_login_pass;
    private javax.swing.JTextArea ta_mensajeEs;
    private javax.swing.JTextField tf_login_user;
    private javax.swing.JTextField tf_register_nombre;
    private javax.swing.JTextField tf_register_password;
    private javax.swing.JTextField tf_register_user;
    // End of variables declaration//GEN-END:variables
    ArrayList<AdminUsers> Users = new ArrayList();
    ArrayList<String> mensajes = new ArrayList();
}
